### ISSUE TITLE
Jwt signature validation is broken when using ClientCredentials together with newer version of Fhi.HelseId

### ISSUE THREAD

**Issue by GeirMG** [FHIDev/Fhi.ClientCredentials#119]
Integration tests fails in for example PersonoppslagApi when we upgrade the ClientCredentials package:
![Image](https://github.com/user-attachments/assets/6b4ea0e4-f630-43be-a68c-4b9b936b36b7)

Commit: baf3be1b

The previous commit (bcf3f2fc) the tests are green.

Using ClientCredentials for example in a console app works fine, but when running this together with Fhi.HelseId, the API stopped being able to validate signature on access tokens. They would fail with the following error message: `IDX10504: Unable to validate signature, token does not have a signature:`. 

This happened because Fhi.ClientCredentials had Microsoft.IdentityModel as a transitive dependency and resolved to a newer version compared to running without Fhi.ClientCredentials. We discovered that between 7.3.1 and 7.4.0, the change introduced by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2491 broke the token validation mechanism in aspnetcore. 

The root cause is described nicely in this comment https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2514#issuecomment-1992452811:
> The issue was introduced by https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/051d164e3c025a0d7276f1d6acf38c902a4893fc: you changed the internal implementation of a static helper in Microsoft.IdentityModel.Tokens and updated OpenIdConnectConfigurationSerializer in Microsoft.IdentityModel.Protocols.OpenIdConnect to use the new logic.
> 
> The thing is, if users only update Microsoft.IdentityModel.Tokens to 7.4.0 (or any package that depends on it, like Microsoft.IdentityModel.JsonWebTokens for instance) without updating Microsoft.IdentityModel.Protocols.OpenIdConnect too, OpenIdConnectConfigurationSerializer will use the new version of the serializer and will be unable to deserialize the configuration properly.

**Comment by GeirMG** [comment]
Trace from Fiddler reveals that /.well-known/openid-configuration/jwks is not called with the new MSAL implementation:
Green box: Before MSAL in ClientCredentials
Red box: With MSAL in ClientCredentials

![Image](https://github.com/user-attachments/assets/922d9f12-abd1-42db-98a9-7639e7880e37)

**Comment by GeirMG** [comment]
https://helseid-sts.test.nhn.no/.well-known/openid-configuration
https://helseid-sts.test.nhn.no/.well-known/openid-configuration/jwks

**Comment by GeirMG** [comment]
https://stackoverflow.com/questions/60635967/idx10500-signature-validation-failed-no-security-keys-were-provided-to-validat

---

I got this issue after an upgrade from .NET 6 to .NET 8. It turned out to be caused by version incompatibilities between Microsoft.IdentityModel.Tokens / Microsoft.IdentityModel.JsonWebTokens and Microsoft.IdentityModel.Protocols.OpenIdConnect.

I was referencing Microsoft.AspNetCore.Authentication.JwtBearer version 8.0.4, which pulled in version 7.1.2 of Microsoft.IdentityModel.Protocols.OpenIdConnect transitively, and at the same time I had referenced version 7.5.1 of Microsoft.IdentityModel.JsonWebTokens. These versions do not work with each other - specifically, this resulted in incompatibilities between some JSON parser code in one package and some JSON parser helpers in another package, which in turns resulted in the jwks_uri being "lost" from the OIDC configuration document when being parsed.

To resolve the issue, make sure to use the same version for all the Microsoft.IdentityModel. packages.

**Comment by martinmine** [comment]
An interesting observation from the Fiddler screenshot is that the jwks_uri is not called. I will have a look at why that is the case.

**Comment by martinmine** [comment]
We have identified that this issue occurs due to upgrade of the NuGet package Microsoft.IdentityModel.JsonWebTokens from version 7.1.2 to 8.2.0.

**Comment by martinmine** [comment]
We have narrowed it down to 7.3.1 and 7.4.0 of this package.

**Comment by martinmine** [comment]
The commit introducing this bug was added here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/2491

**Comment by GeirMG** [comment]
A workaround has been suggested here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2514

Workaround: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2514#issuecomment-1986893951

**Comment by GeirMG** [comment]
Another thread describing the issue: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/2670

**Comment by GeirMG** [comment]
"Duende IdentityServer, the Microsoft external authentication handlers and other libraries all use the Microsoft.IdentityModel set of libraries. These libraries provides token and configuration handling features. The functionality is split up between different libraries and they all need to be exactly the same version. However this is not enfored by Nuget so it is common to end up with an application that brings in different versions of Microsoft.IdentityModel.* through transitive dependencies."

https://docs.duendesoftware.com/identityserver/v7/troubleshooting/wilson/
